### ISSUE TITLE
Uchiwa is restarted every chef run

### ISSUE THREAD

**Issue by nickm4062** [sensu/uchiwa-chef#22] opened 2014-12-30 21:43 UTC
Currently uchiwa is restarted every chef run

**Comment by nickm4062** [comment] 2015-01-06 00:44
RHEL65 when using multiple api sources

**Comment by portertech** [comment] 2015-01-06 02:13
@amdprophet ping.

**Comment by amdprophet** [comment] 2015-01-06 02:43
@nickm4062 I'll have the JSON sorting fix done soon; can you compare last modified dates of the uchiwa config between converges and see if it changes?

**Comment by drpebcak** [comment] 2015-01-06 06:24
@nickm4062 ah, I've only got one api source currently.

**Comment by nickm4062** [comment] 2015-01-06 21:01
@amdprophet will let you know shortly

**Comment by nickm4062** [comment] 2015-01-08 19:55
One converge to the next

[root@n7-z01-0a2a0b6b sensu]# stat uchiwa.json
  File: `uchiwa.json'
  Size: 563       	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 17758       Links: 1
Access: (0640/-rw-r-----)  Uid: (  497/  uchiwa)   Gid: (  497/  uchiwa)
Access: 2015-01-08 11:53:16.434547644 -0800
Modify: 2015-01-08 11:52:03.563547644 -0800
Change: 2015-01-08 11:53:06.477547644 -0800

[root@n7-z01-0a2a0b6b sensu]# stat uchiwa.json
  File: `uchiwa.json'
  Size: 563       	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 17758       Links: 1
Access: (0640/-rw-r-----)  Uid: (  497/  uchiwa)   Gid: (  497/  uchiwa)
Access: 2015-01-08 11:54:46.715547644 -0800
Modify: 2015-01-08 11:52:03.563547644 -0800
Change: 2015-01-08 11:54:35.654547644 -0800

**Comment by amdprophet** [comment] 2015-02-27 20:47
@nickm4062 sorry for the delay - it looks like uchiwa.json is getting changed each run. I've already done some work to fix this and should have it pushed sometime next week.

**Comment by majormoses** [comment] 2017-04-04 17:27
@amdprophet I know this has been a while any chance of getting this worked on?

**Comment by majormoses** [comment] 2017-11-14 00:54
Pretty sure this is no longer an issue. Not sure where it got fixed or if there is something we are doing in our wrapper to account for this. Due to the age and lack of reproducibility I think we should close this and let someone open with a new issue (please link it) if we are seeing it.

**Closed by majormoses** 2017-11-14 00:54 UTC
